In [4]:
import gym 
import numpy as np

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [5]:
env = gym.make('FrozenLake-v1', is_slippery=False)

/usr/local/lib/python3.7/site-packages/gym/core.py:318: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."
/usr/local/lib/python3.7/site-packages/gym/wrappers/step_api_compatibility.py:40: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  "Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future."


In [21]:
epsilon = 1.0
epsilon_decay = 0.995
epsilon_min = 0.01
total_episodes = 1000
max_steps = 100
alpha = 0.85
gamma = 0.95

In [15]:
Q = np.zeros((env.observation_space.n, env.action_space.n))

In [16]:
def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        return env.action_space.sample() # explore randomly
    else:
        return np.argmax(Q[state, :])    # exploit the best known action
    

In [17]:
def update(state, state2, reward, action, done):
    predict = Q[state, action]
    
    if done:
        target = reward
    else:
        target = reward + gamma * np.max(Q[state2, :])
    
    Q[state, action] = Q[state, action] + alpha * (target - predict)

In [25]:
for episode in range(total_episodes):
    state = env.reset()
    action = choose_action(state)
    
    for t in range(max_steps):
        next_state, reward, done, _ = env.step(action)
        update(state, next_state, reward, action, done)
        state = next_state
        action = choose_action(state)
        
        if done:
            break
            
        epsilon = max(epsilon_min, epsilon * epsilon_decay)

In [26]:
total_reward = 0

for _ in range(100):
    state = env.reset()
    while True:
        action = np.argmax(Q[state, :])
        next_state, reward, done, _ = env.step(action)
        total_reward += reward
        state = next_state
        
        if done: break
            
print("Average Reward: ", total_reward / 100)

Average Reward:  0.61


In [27]:
print(Q)

[[1.08888218e-01 8.25071127e-03 1.29271471e-02 1.63703283e-02]
 [6.24231637e-05 2.74020842e-03 7.63063549e-05 6.59139938e-02]
 [3.23061221e-02 7.29918169e-04 3.51280078e-04 2.20314262e-05]
 [1.46803592e-05 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.43826759e-01 4.10527806e-03 5.87886626e-05 6.97007541e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.02500492e-01 3.40548716e-08 2.14476189e-05 5.84994930e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.28539113e-02 3.61946129e-02 8.78170402e-02 4.00338942e-01]
 [1.77915016e-02 7.79167338e-01 1.90638162e-02 1.40411979e-02]
 [5.04025275e-01 1.34238819e-02 7.35349436e-05 1.09282637e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.82049294e-02 1.21827516e-01 9.32007702e-01 3.39960533e-04]
 [9.19363420e-02 1.48830773e-01 1.16472676e-01 9.98656140e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000